import { Screen, Button, Field, Row } from '../components/UI';

export function WelcomeScreen({ navigation }: any) {
  return <Screen title="DigitalStep" subtitle="A simple marketing manager for small businesses. Plan your next move, keep campaigns organized, and stay consistent."><Button label="Log in" onPress={() => navigation.navigate('Login')} /><Button secondary label="Create account" onPress={() => navigation.navigate('Register')} /></Screen>;
}
export function LoginScreen({ navigation }: any) { return <Screen title="Welcome back" subtitle="Log in to manage today’s marketing."><Field placeholder="Email" autoCapitalize="none" /><Field placeholder="Password" secureTextEntry /><Button label="Log in" onPress={() => navigation.replace('Main')} /></Screen>; }
export function RegisterScreen({ navigation }: any) { return <Screen title="Create account" subtitle="Start organizing your business marketing in minutes."><Field placeholder="Name" /><Field placeholder="Email" autoCapitalize="none" /><Field placeholder="Password" secureTextEntry /><Button label="Continue" onPress={() => navigation.navigate('BusinessOnboarding')} /></Screen>; }
export function BusinessOnboardingScreen({ navigation }: any) { return <Screen title="Tell us about your business" subtitle="DigitalStep uses this to shape your dashboard and default marketing plan."><Field placeholder="Business name" /><Field placeholder="Industry" /><Field placeholder="Primary marketing goal" /><Field placeholder="Main channels" /><Button label="Finish setup" onPress={() => navigation.replace('Main')} /></Screen>; }
export function HomeScreen() { return <Screen title="Dashboard" subtitle="Your marketing at a glance."><Row title="Today’s focus" detail="Post the weekly special and review the Friday email draft." /><Row title="Active campaign" detail="Weekday Breakfast Push is active through the next two weeks." /><Row title="Next planned content" detail="Behind the scenes reel scheduled for Instagram." /></Screen>; }
export function TasksScreen() { return <Screen title="Today’s tasks" subtitle="Small steps that keep marketing moving."><Row title="Post weekly pastry special" detail="Due today · Instagram" /><Row title="Draft Friday email" detail="Due tomorrow · In progress" /><Row title="Review campaign photos" detail="This week · To do" /></Screen>; }
export function PlannerScreen() { return <Screen title="Content planner" subtitle="Capture ideas, drafts, and scheduled content."><Row title="Behind the scenes: sourdough prep" detail="Scheduled · Instagram reel" /><Row title="June loyalty offer" detail="Draft · Email" /><Row title="Customer spotlight" detail="Idea · Facebook" /></Screen>; }
export function CalendarScreen() { return <Screen title="Calendar" subtitle="A mobile-first view of upcoming marketing moments."><Row title="Today" detail="Post weekly pastry special" /><Row title="Tomorrow" detail="Finish Friday email" /><Row title="Next week" detail="Plan July local partnership campaign" /></Screen>; }
export function CampaignsScreen() { return <Screen title="Campaigns" subtitle="Track focused marketing pushes without extra complexity."><Row title="Weekday Breakfast Push" detail="Active · Drive 15% more weekday morning orders" /><Row title="Summer Catering Leads" detail="Planned · Collect event inquiries" /></Screen>; }
export function RecommendationsScreen() { return <Screen title="Recommendations" subtitle="Practical, non-AI suggestions based on your plan and schedule."><Row title="Promote best-selling item earlier" detail="Schedule coffee-and-pastry content before 8 AM." /><Row title="Add a recurring planning block" detail="Reserve 30 minutes every Monday for content planning." /></Screen>; }
export function SettingsScreen() { return <Screen title="Settings" subtitle="Manage account, business profile, and workspace preferences."><Row title="Business profile" detail="Bloom & Bean Cafe" /><Row title="Channels" detail="Instagram, Facebook, Email" /><Button secondary label="Log out" onPress={() => {}} /></Screen>; }
